#!/bin/bash -e

#####################################################################
#                                                                   #
#            Compiles Faust programs to the disting NT              #
#                                                                   #
#####################################################################

. faustpath

temp=$2.cpp

faust -a $FAUSTARCH/nt_arch.cpp -uim -nvi -mem -o $temp $1
python3 $FAUSTARCH/remove_small_arrays.py $temp
python3 $FAUSTARCH/apply_metadata.py $temp
arm-none-eabi-c++ -std=c++11 -mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -fno-exceptions -Os -fPIC -Wall -I$NT_API_PATH/include -c -o $2 $temp
rm $temp
